"""
Auto-generated by tools/derive_symbolic_model.py - do not edit by hand.

Plain numpy implementations of the two-locus selection model's
one-generation allele-frequency change and its Jacobian, for an arbitrary
3x3 fitness matrix w (flattened row-major as w0..w8: rows = genotype at
locus A [AA, Aa, aa], columns = genotype at locus B [BB, Bb, bb]). These
were derived symbolically once - see tools/derive_symbolic_model.py - and
hardcoded here so the shipped app does not need sympy at runtime. Inputs
fA, fB may be scalars or numpy arrays of matching shape.
"""

import numpy as np


def delta_fA_fn(fA, fB, w0, w1, w2, w3, w4, w5, w6, w7, w8):
    """One-generation change in the frequency of allele A."""
    return (
        fA**2
        * (fB**2 * w0 + 2 * fB * w1 * (1 - fB) + w2 * (1 - fB) ** 2)
        / (
            fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
            + 2
            * fB
            * (1 - fB)
            * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
            + (1 - fB) ** 2 * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
        )
        + 2
        * fA
        * (1 - fA)
        * (fB**2 * w3 + 2 * fB * w4 * (1 - fB) + w5 * (1 - fB) ** 2)
        / (
            2 * fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
            + 4
            * fB
            * (1 - fB)
            * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
            + 2
            * (1 - fB) ** 2
            * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
        )
        - fA
    )


def delta_fB_fn(fA, fB, w0, w1, w2, w3, w4, w5, w6, w7, w8):
    """One-generation change in the frequency of allele B."""
    return (
        fB**2
        * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
        / (
            fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
            + 2
            * fB
            * (1 - fB)
            * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
            + (1 - fB) ** 2 * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
        )
        + 2
        * fB
        * (1 - fB)
        * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
        / (
            2 * fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
            + 4
            * fB
            * (1 - fB)
            * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
            + 2
            * (1 - fB) ** 2
            * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
        )
        - fB
    )


def jacobian_fn(fA, fB, w0, w1, w2, w3, w4, w5, w6, w7, w8):
    """Jacobian of (delta_fA, delta_fB) with respect to (fA, fB), as a
    2x2 numpy array. fA, fB must be scalars for this to be a proper 2x2
    matrix (this is only ever evaluated at a single point, e.g. inside
    the equilibrium solver)."""
    return np.array(
        [
            [
                fA**2
                * (fB**2 * w0 + 2 * fB * w1 * (1 - fB) + w2 * (1 - fB) ** 2)
                * (
                    -(fB**2)
                    * (
                        2 * fA * w0
                        - 2 * fA * w3
                        + 2 * w3 * (1 - fA)
                        + w6 * (2 * fA - 2)
                    )
                    - 2
                    * fB
                    * (1 - fB)
                    * (
                        2 * fA * w1
                        - 2 * fA * w4
                        + 2 * w4 * (1 - fA)
                        + w7 * (2 * fA - 2)
                    )
                    - (1 - fB) ** 2
                    * (
                        2 * fA * w2
                        - 2 * fA * w5
                        + 2 * w5 * (1 - fA)
                        + w8 * (2 * fA - 2)
                    )
                )
                / (
                    fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                ** 2
                + 2
                * fA
                * (1 - fA)
                * (fB**2 * w3 + 2 * fB * w4 * (1 - fB) + w5 * (1 - fB) ** 2)
                * (
                    -2
                    * fB**2
                    * (
                        2 * fA * w0
                        - 2 * fA * w3
                        + 2 * w3 * (1 - fA)
                        + w6 * (2 * fA - 2)
                    )
                    - 4
                    * fB
                    * (1 - fB)
                    * (
                        2 * fA * w1
                        - 2 * fA * w4
                        + 2 * w4 * (1 - fA)
                        + w7 * (2 * fA - 2)
                    )
                    - 2
                    * (1 - fB) ** 2
                    * (
                        2 * fA * w2
                        - 2 * fA * w5
                        + 2 * w5 * (1 - fA)
                        + w8 * (2 * fA - 2)
                    )
                )
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                ** 2
                + 2
                * fA
                * (fB**2 * w0 + 2 * fB * w1 * (1 - fB) + w2 * (1 - fB) ** 2)
                / (
                    fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                - 2
                * fA
                * (fB**2 * w3 + 2 * fB * w4 * (1 - fB) + w5 * (1 - fB) ** 2)
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                + 2
                * (1 - fA)
                * (fB**2 * w3 + 2 * fB * w4 * (1 - fB) + w5 * (1 - fB) ** 2)
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                - 1,
                fA**2
                * (fB**2 * w0 + 2 * fB * w1 * (1 - fB) + w2 * (1 - fB) ** 2)
                * (
                    -2 * fB * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    - 2
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    - (2 * fB - 2)
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                / (
                    fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                ** 2
                + fA**2
                * (2 * fB * w0 - 2 * fB * w1 + 2 * w1 * (1 - fB) + w2 * (2 * fB - 2))
                / (
                    fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                + 2
                * fA
                * (1 - fA)
                * (fB**2 * w3 + 2 * fB * w4 * (1 - fB) + w5 * (1 - fB) ** 2)
                * (
                    -4 * fB * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    - 4
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    - 2
                    * (2 * fB - 2)
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                ** 2
                + 2
                * fA
                * (1 - fA)
                * (2 * fB * w3 - 2 * fB * w4 + 2 * w4 * (1 - fB) + w5 * (2 * fB - 2))
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                ),
            ],
            [
                fB**2
                * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                * (
                    -(fB**2)
                    * (
                        2 * fA * w0
                        - 2 * fA * w3
                        + 2 * w3 * (1 - fA)
                        + w6 * (2 * fA - 2)
                    )
                    - 2
                    * fB
                    * (1 - fB)
                    * (
                        2 * fA * w1
                        - 2 * fA * w4
                        + 2 * w4 * (1 - fA)
                        + w7 * (2 * fA - 2)
                    )
                    - (1 - fB) ** 2
                    * (
                        2 * fA * w2
                        - 2 * fA * w5
                        + 2 * w5 * (1 - fA)
                        + w8 * (2 * fA - 2)
                    )
                )
                / (
                    fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                ** 2
                + fB**2
                * (2 * fA * w0 - 2 * fA * w3 + 2 * w3 * (1 - fA) + w6 * (2 * fA - 2))
                / (
                    fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                + 2
                * fB
                * (1 - fB)
                * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                * (
                    -2
                    * fB**2
                    * (
                        2 * fA * w0
                        - 2 * fA * w3
                        + 2 * w3 * (1 - fA)
                        + w6 * (2 * fA - 2)
                    )
                    - 4
                    * fB
                    * (1 - fB)
                    * (
                        2 * fA * w1
                        - 2 * fA * w4
                        + 2 * w4 * (1 - fA)
                        + w7 * (2 * fA - 2)
                    )
                    - 2
                    * (1 - fB) ** 2
                    * (
                        2 * fA * w2
                        - 2 * fA * w5
                        + 2 * w5 * (1 - fA)
                        + w8 * (2 * fA - 2)
                    )
                )
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                ** 2
                + 2
                * fB
                * (1 - fB)
                * (2 * fA * w1 - 2 * fA * w4 + 2 * w4 * (1 - fA) + w7 * (2 * fA - 2))
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                ),
                fB**2
                * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                * (
                    -2 * fB * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    - 2
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    - (2 * fB - 2)
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                / (
                    fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                ** 2
                + 2
                * fB
                * (1 - fB)
                * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                * (
                    -4 * fB * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    - 4
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    - 2
                    * (2 * fB - 2)
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                ** 2
                + 2
                * fB
                * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                / (
                    fB**2 * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 2
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                - 2
                * fB
                * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                + 2
                * (1 - fB)
                * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                / (
                    2
                    * fB**2
                    * (fA**2 * w0 + 2 * fA * w3 * (1 - fA) + w6 * (1 - fA) ** 2)
                    + 4
                    * fB
                    * (1 - fB)
                    * (fA**2 * w1 + 2 * fA * w4 * (1 - fA) + w7 * (1 - fA) ** 2)
                    + 2
                    * (1 - fB) ** 2
                    * (fA**2 * w2 + 2 * fA * w5 * (1 - fA) + w8 * (1 - fA) ** 2)
                )
                - 1,
            ],
        ]
    )
