"""
Regenerates src/evolution_models/_generated_symbolic.py.

Run this only when the underlying two-locus selection model itself
changes (e.g. a different fitness scheme, or extending it to more loci).
It is not part of the shipped app: it is the only place in the project
that imports sympy, and it writes out plain numpy functions so nothing
downstream needs sympy at runtime (sympy would be a large, slow-to-import
dependency to ship into a Pyodide/WebAssembly build).

Usage:
    python tools/derive_symbolic_model.py
"""

import subprocess
from pathlib import Path

import sympy as sp
from sympy.printing.numpy import NumPyPrinter

OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "evolution_models"
    / "_generated_symbolic.py"
)


def derive_expressions() -> tuple[sp.Expr, sp.Expr, sp.Matrix]:
    """Derive the two-locus selection model's frequency-change expressions
    and their Jacobian, symbolically, for a general 3x3 fitness matrix.

    Returns (delta_fA_expr, delta_fB_expr, jacobian_matrix), all in terms
    of the symbols fA, fB, w0, ..., w8 (w flattened row-major: rows =
    genotype at locus A [AA, Aa, aa], columns = genotype at locus B
    [BB, Bb, bb]). Assumes the two loci are in linkage equilibrium, so
    genotype frequencies at each locus follow independent Hardy-Weinberg
    proportions.
    """
    fA, fB = sp.symbols("fA fB", real=True)
    w_symbols = list(sp.symbols("w0:9"))
    w_matrix = sp.Matrix(3, 3, w_symbols)

    fa, fb = 1 - fA, 1 - fB
    genotype_freqs_A = sp.Matrix([fA**2, 2 * fA * fa, fa**2])  # AA, Aa, aa
    genotype_freqs_B = sp.Matrix([fB**2, 2 * fB * fb, fb**2])  # BB, Bb, bb

    mean_fitness = (genotype_freqs_A.T * w_matrix * genotype_freqs_B)[0]
    marginal_fitness_A = w_matrix * genotype_freqs_B
    marginal_fitness_B = w_matrix.T * genotype_freqs_A

    delta_fA_expr = (
        genotype_freqs_A[0] * marginal_fitness_A[0] / mean_fitness
        + genotype_freqs_A[1] * marginal_fitness_A[1] / (2 * mean_fitness)
        - fA
    )
    delta_fB_expr = (
        genotype_freqs_B[0] * marginal_fitness_B[0] / mean_fitness
        + genotype_freqs_B[1] * marginal_fitness_B[1] / (2 * mean_fitness)
        - fB
    )
    # sp.simplify is deliberately skipped: with w left symbolic it is
    # noticeably slower to run and does not shorten the generated code in
    # a way that matters once it is just arithmetic evaluated by numpy.

    jacobian_matrix = sp.Matrix(
        [
            [sp.diff(delta_fA_expr, fA), sp.diff(delta_fA_expr, fB)],
            [sp.diff(delta_fB_expr, fA), sp.diff(delta_fB_expr, fB)],
        ]
    )
    return delta_fA_expr, delta_fB_expr, jacobian_matrix


def render_module(
    delta_fA_expr: sp.Expr, delta_fB_expr: sp.Expr, jacobian_matrix: sp.Matrix
) -> str:
    """Render the derived expressions as a self-contained Python module
    source, using only plain arithmetic (no sympy at import time)."""
    printer = NumPyPrinter()
    args = "fA, fB, w0, w1, w2, w3, w4, w5, w6, w7, w8"

    delta_fA_src = printer.doprint(delta_fA_expr)
    delta_fB_src = printer.doprint(delta_fB_expr)
    jacobian_src = [
        [printer.doprint(jacobian_matrix[i, j]) for j in range(2)] for i in range(2)
    ]

    return f'''"""
Auto-generated by tools/derive_symbolic_model.py - do not edit by hand.

Plain numpy implementations of the two-locus selection model's
one-generation allele-frequency change and its Jacobian, for an arbitrary
3x3 fitness matrix w (flattened row-major as w0..w8: rows = genotype at
locus A [AA, Aa, aa], columns = genotype at locus B [BB, Bb, bb]). These
were derived symbolically once - see tools/derive_symbolic_model.py - and
hardcoded here so the shipped app does not need sympy at runtime. Inputs
fA, fB may be scalars or numpy arrays of matching shape.
"""

import numpy as np


def delta_fA_fn({args}):
    """One-generation change in the frequency of allele A."""
    return {delta_fA_src}


def delta_fB_fn({args}):
    """One-generation change in the frequency of allele B."""
    return {delta_fB_src}


def jacobian_fn({args}):
    """Jacobian of (delta_fA, delta_fB) with respect to (fA, fB), as a
    2x2 numpy array. fA, fB must be scalars for this to be a proper 2x2
    matrix (this is only ever evaluated at a single point, e.g. inside
    the equilibrium solver)."""
    return np.array(
        [
            [{jacobian_src[0][0]}, {jacobian_src[0][1]}],
            [{jacobian_src[1][0]}, {jacobian_src[1][1]}],
        ]
    )
'''


def main() -> None:
    delta_fA_expr, delta_fB_expr, jacobian_matrix = derive_expressions()
    module_source = render_module(delta_fA_expr, delta_fB_expr, jacobian_matrix)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(module_source)
    try:
        subprocess.run(["black", "-q", str(OUTPUT_PATH)], check=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass  # formatting is cosmetic only; the file is valid either way
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
